name: Add issues to `Bsuir Schedule App` project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/asiliuk/projects/3
          github-token: ${{ secrets.BSUIR_PROJECT_PAT }}
